#! /bin/sh

case "$1" in
    start)
        # If the argument is "start", print a message and start the scull daemon
        echo "Starting init script for scull Loading"
        if ! lsmod | grep -q scull; then
            start-stop-daemon -S -n init -a /usr/bin/scull_load
        fi
        ;;
    stop)
        # If the argument is "stop", print a message and stop the scull daemon
        echo "Removing user scull_load"
        start-stop-daemon -K -n scull_load
        start-stop-daemon -S -n init -a /usr/bin/scull_unload
        ;;
    *)
        # If the argument is not "start" or "stop", print usage information and exit with an error code
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

# Exit the script successfully
exit 0